### ISSUE TITLE
403 Unauthorized when auth_gss_allow_basic_fallback off

### ISSUE THREAD

**Issue by serkanz** [stnoonan/spnego-http-auth-nginx-module#104]
I'm trying to setup an **nginx server (1.19.0)** on **Ubuntu (18.04)** which uses current version of **spnego-http-auth-nginx-module**.

I successfully built nginx with spnego module, and it works as expected without auth_gss enabled. 

I set up my keytab file as stated in [ifad's fork](https://github.com/ifad/spnego-http-auth-nginx-module/blob/master/README.md).    

With this keytab file, when I run command

```
kinit -5 -V -k -t /usr/local/nginx/krb5.keytab HTTP/deneme.aaa.com
```

I successfuly get the message 

```
Using default cache: /tmp/krb5cc_1000
Using principal: HTTP/deneme.aaa.com@DOMAIN.COM.TR
Using keytab: krb5.keytab
Authenticated to Kerberos v5
```
and klist -k krb5.keytab command shows 

```
Keytab name: FILE:krb5.keytab
KVNO Principal
---- --------------------------------------------------------------------------
   4 host/deneme.aaa.com@DOMAIN.COM.TR
   6 HTTP/deneme.aaa.com@DOMAIN.COM.TR
```

```
user  root root;                                             
worker_processes  1;                                         
                                                             
#pid        logs/nginx.pid;                                  
                                                             
events {                                                     
    worker_connections  1024;                                
}                                                            
                                                             
http {                                                       
    include       mime.types;                                
    default_type  application/octet-stream;                  
                                                             
    sendfile        on;                                      
                                                             
    # HTTPS server                                           
    #                                                        
    server {                                                 
        listen       443 ssl;                                
        server_name  deneme.aaa.com;              
                                                             
        ssl_certificate      /home/user/public.crt;  
        ssl_certificate_key  /home/user/private.rsa; 
                                                             
        ssl_session_cache    shared:SSL:1m;                  
        ssl_session_timeout  5m;                             
                                                             
        location / {                                         
            root   html;                                     
            index  index.html index.htm;                     
            auth_gss on;                                     
            auth_gss_allow_basic_fallback off;               
        }                                                    
    }                                                        
}                                                            
```

With the configuration above, when I hit the page https://deneme.aaa.com, I get 403 unauthorized error withput any login prompt. There's no logs in logs/error.log. In the access.log 

```
192.168.106.1 - - [24/Jun/2020:11:26:29 +0300] "GET / HTTP/1.1" 401 581 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
192.168.106.1 - - [24/Jun/2020:11:26:29 +0300] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
```

When I make 
```
auth_gss_allow_basic_fallback on;      
```

login prompt appears and with the correct credentials I can access the index page, but this is because basic authentication works.

When I hit the page from browser and run klist on the client machine I can see the Kerberos tickets are issued.

What could be the reason? Should I use the older version of nginx?

Kind regards

**Comment by jheiss** [comment]
Have you tried setting `auth_gss_keytab`? Given that your keytab is not in a standard location I expect without that (or the `KRB5_KTNAME` environment variable) nginx isn't finding your keytab and then probably not enabling Kerberos authentication.

**Comment by serkanz** [comment]
> Have you tried setting `auth_gss_keytab`? Given that your keytab is not in a standard location I expect without that (or the `KRB5_KTNAME` environment variable) nginx isn't finding your keytab and then probably not enabling Kerberos authentication.

I tried to set both **auth_gss_keytab** and **default_keytab_name** at **krb5.conf** file. However that didn't help. When I enter the wrong service name or so I get error and it's written in error.log file.

**Comment by jheiss** [comment]
Looking closer, your logs indicate a 401, followed by a 403. Have you tried connecting with curl or another CLI client (or inspect the headers in your browser) to see if the 401 response includes a `www-authenticate: negotiate` header? It may be that the server is doing the right thing but your browser is not. E.g.

```
$ curl -i https://deneme.aaa.com
HTTP/1.1 401 Unauthorized
Server: nginx/blah
WWW-Authenticate: Negotiate
```

**Comment by serkanz** [comment]
> Looking closer, your logs indicate a 401, followed by a 403. Have you tried connecting with curl or another CLI client (or inspect the headers in your browser) to see if the 401 response includes a `www-authenticate: negotiate` header? It may be that the server is doing the right thing but your browser is not. E.g.
> 
> ```
> $ curl -i https://deneme.aaa.com
> HTTP/1.1 401 Unauthorized
> Server: nginx/blah
> WWW-Authenticate: Negotiate
> ```

I didn't use curl but I tried to intercept browser requests with Fiddler and first request to the nginx is responded with `www-authenticate: negotiate` header and then browser responds with kerberos ticket. And on the client machine when I run klist, it lists the ticket. I'm now trying to buld nginx with debug mode on.

**Comment by serkanz** [comment]
I think the problem is with encryption alghorithm. In the debug logs : 

****2020/06/24 20:33:45 [debug] 77693#0: *60 gss_accept_sec_context() failed: Request ticket server HTTP/deneme.aaa.com@DOMAIN.COM.TR kvno 4 found in keytab but not with enctype rc4-hmac:****

How can I accept other encryption types also?

```
2020/06/24 20:33:45 [debug] 77693#0: *60 Token decoded: YIIH/QYGKwYBBQUCoIIH8TCCB+2gMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCB7cEggezYIIHrwYJKoZIhvcSAQICAQBuggeeMIIHmqADAgEFoQMCAQ6iBwMFACAAAACjggXHYYIFwzCCBb+gAwIBBaEMGwpTU00uR09WLlRSoiwwKqADAgECoSMwIRsESFRUUBsZa2VyYmVyb3NkZW5lbWUuc3NiLmdvdi50cqOCBXowggV2oAMCARehAwIBBKKCBWgEggVk7AYHg4uKWmTAC7UjUhqwwWLwxdxg7r00b2nZMAwfJtYcBDdN2nH7qT7sRIhJTJ4hr60pvccsHZ9AxzFCkdgtajb1JJIbcA7htETsuZEu04qJZslds9lTkTmYwebXkOWMHOx0ZKAcVl/DmuJ+M8uoy6UGhsgzVi1+cgH5LsUMjNRVRFN3XgZNiiXqwfBr2yOCDDFx7f92YSacOJMr2EXc01f4MR21WDxy8ceOOemlfto9jHNIzfjMjPAKsk0ezqUJxqCYD7UPohErehxWHut++3T5eoKSlnSpcF0G1PqQYduByld3twUbDJE4wwT6YisEzzn7xc3YBfqJ8KjXjIqPqx8IzS/wQX2z4LBfZuZcdymh1hklL6tfmSxUnewCsWRg67LXrO1BrFql0uyD9XwWAVtjrgJwIsbU5I9sgeOWnXIqBMNe8fQvJgzTqV7BOV3hCAzZodCZy1DGCdJDivoqW8K9uk85YPhkQSijv03nFzRl/CS/WiKWzryBtZFdIH1nMACSmGQYd+ibgBBE8GaDe3s4mY1ep6W74d055UMzSitYLRfzVOMHYPz00HbYplg0aHU1FjC/QSYXaij42YiJJUa9xI4zIjJEu87tO80XQyqFFybsGauTPmUCQPThbq4iXgsMKsWY3Jkh4rBsaIKp/LD/IrWLtb42ROs1lATIwxalUW6I0ewsY969iWQpy8hFFJRJ7J/gtXfVi1iKGTX6+nKqvjy6FLGcqnyYT1Od2cRYVdg46gliJXtGQMTzVnZjcQSlqTgL3QzZwGpEiN/UNCA8y3s9bii0TUCo1ivO3quV449SIo9QDKIs+e2oKcI2s4MjUZU+/YHycG8FL5Y8CZpXlGdpshxlXK0CCKEbHPvHMTqnJF9J8v9Mp2bP7/TOrOs8fh7R2wEAQBj0pntiwSKvPPX53A415+qXxg1YhzXOWAV6MkTH//VtmRxT9A7UT3FjrqunyQ1LQDly0Cd1cn2Fdgm3XjCY9KKIwGkFHU5Rr7koCbAWLzYruts9kGsYzpBjW2e903tB0XRcV0Am62MApXiK5fsBhnfUqYJRmSBROaJUz7+qNN5UhDBIUbcqnOoSzGD2sivuDqatgqUNfS1ImhXhCE9820L/NAQnvZF86KyjrkhHxw6P7/e+J1uqM6gScUnjlejGuDYCRmWak2YHmTCaH0nGsBie9HYsoDa6OporSSOpLaK/vDrpU3O6GGw5PWxQT21I55vC6yIgtfYBVBE595mZOjbNf7cngcFpJGX9fbQ9c95zl7ph7iaj/nnd0FHgbglF3TsPj6BxVuQOamxAl4mc8ZjG8RDxZFXAjGbZEVqD6skQfTCfY4tQIX4bSDpRtYwmtM80fdvZP8pMDEirwl8f2lTvGkz5jVErRFiDk1EkfATE90BpUF0Ep6t3acXQh3VNNHe34yG1Pa8zB2hgOratP7nEydcJ5oBwTME/oqf2pRkAzN7+B+89EVPk0iSxS/uqvCBiP41G5ONF2r1hHPgk9SOvEm80C+vzx9IT781f6CX58aSTOqe/nj2un9Qw4fL2IaY3lGMb9b2jkalcHh1/de94BpG4TgjSdiJrt8HIl3PmeoUR3OCdbZtotVYF//TeT0Krn+dkTrsIm14FNLqXLaTUlWJtbWGCbnMOQENqkdSc4cqUxcTPk+356ogZ7vGRJ5FCfT04oGa390h
2020/06/24 20:33:45 [debug] 77693#0: *60 Client sent a reasonable Negotiate header
2020/06/24 20:33:45 [debug] 77693#0: *60 GSSAPI authorizing
2020/06/24 20:33:45 [debug] 77693#0: *60 Use keytab sppsadmin.keytab
2020/06/24 20:33:45 [debug] 77693#0: *60 gss_accept_sec_context() failed: Request ticket server HTTP/deneme.aaa.com@DOMAIN.COM.TR kvno 4 found in keytab but not with enctype rc4-hmac:
2020/06/24 20:33:45 [debug] 77693#0: *60 GSSAPI failed
2020/06/24 20:33:45 [debug] 77693#0: *60 http finalize request: 403, "/favicon.ico?" a:1, c:1
2020/06/24 20:33:45 [debug] 77693#0: *60 http special response: 403, "/favicon.ico?"
2020/06/24 20:33:45 [debug] 77693#0: *60 http set discard body
2020/06/24 20:33:45 [debug] 77693#0: *60 HTTP/1.1 403 Forbidden
Server: nginx/1.18.0
Date: Wed, 24 Jun 2020 17:33:45 GMT
Content-Type: text/html
Content-Length: 555
Connection: keep-alive
```

**Comment by hawicz** [comment]
Try re-doing the [ktpass step](https://github.com/ifad/spnego-http-auth-nginx-module/blob/master/README.md#crash-course-to-windows-kdc-configuration), but specify `-crypto rc5-hmac-nt`.

**Comment by serkanz** [comment]
> Try re-doing the [ktpass step](https://github.com/ifad/spnego-http-auth-nginx-module/blob/master/README.md#crash-course-to-windows-kdc-configuration), but specify `-crypto rc4-hmac-nt`.

Before trying this , I want to change the service account's setting to enable Aes 256 bit encryption. As rc4-hmac is a bit old, it might be better to use Aes. If it doesn't help, I'll recreate keytab files with rc4-hmac.

**Comment by serkanz** [comment]
I successfuly authenticated user when service account's (HTTP/deneme.aaa.com@DOMAIN.COM.TR) **"This account supports Kerberos AES 256 bit encryption"** setting is enabled in Active Directory Users and Computers. 

When it's not enabled, Active Directory doesn't send **AES-256-CTS-HMAC-SHA1-96** encrypted Kerberos ticket, instead it sends RC4-HMAC which is not acceptable by keytab file and NGINX.

Thanks for sorting it out.

**Comment by Dimazxc** [comment]
> I successfuly authenticated user when service account's (HTTP/[deneme.aaa.com@DOMAIN.COM.TR](mailto:deneme.aaa.com@DOMAIN.COM.TR)) **"This account supports Kerberos AES 256 bit encryption"** setting is enabled in Active Directory Users and Computers.
> 
> When it's not enabled, Active Directory doesn't send **AES-256-CTS-HMAC-SHA1-96** encrypted Kerberos ticket, instead it sends RC4-HMAC which is not acceptable by keytab file and NGINX.
> 
> Thanks for sorting it out.

Hello, may be you could help me. I got the same 401 then 403 error. Are you set "This account supports Kerberos AES 256 bit encryption" option for service account HTTP/deneme.aaa.com@DOMAIN.COM.TR or for all ad users account which gonna connect to the application?
