### ISSUE TITLE
Erro while building with nginx 1.19.2

### ISSUE THREAD

**Issue by VasistaPolali** [stnoonan/spnego-http-auth-nginx-module#107]
When building the module with nginx 1.19.2 i am seeing an error as below.Any inputs are appreciated.

spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.c:933:28: error: implicit declaration of function 'gss_localname' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            major_status = gss_localname(&minor_status, client_name,
                           ^
1 error generated.
make[1]: *** [objs/addon/spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.o] Error 1
make: *** [build] Error 2

**Comment by stnoonan** [comment]
From the readme:

> Note that if it isn't clear, you do need KRB5 (MIT or Heimdal) header files installed. On Debian based distributions, including Ubuntu, this is the krb5-multidev, libkrb5-dev, heimdal-dev, or heimdal-multidev package depending on your environment. On other Linux distributions, you want the development libraries that provide gssapi_krb5.h.

So you're likely missing some of the dependencies.
