### ISSUE TITLE
Creation of KeyTab file.

### ISSUE THREAD

**Issue by chaisacchu** [stnoonan/spnego-http-auth-nginx-module#109]
@stnoonan Keytab file creation wasn't mentioned here. If we are integrating against MS Active Directory. Do we need to create KeyTab file in Active Directory or in nginx server?. It will really help if you provide your comments.

**Comment by fx02** [comment]
You need to create user in AD and then create keytab file assigned to that user. One user per keytab file. Example:
`ktpass -princ host/nginxsso.yourdomain.local@YOURDOMAIN.LOCAL -mapuser adusername@YOURDOMAIN.LOCAL -crypto ALL -ptype KRB5_NT_PRINCIPAL -pass somecoolpassword -target dc0.yourdomain.local -out host.keytab`

**Comment by stnoonan** [comment]
Also take a look at https://github.com/stnoonan/spnego-http-auth-nginx-module/pull/91 which includes some other instructions for AD.
