### ISSUE TITLE
Incomplete error message: gss_accept_sec_context() failed: :

### ISSUE THREAD

**Issue by wojnosystems** [stnoonan/spnego-http-auth-nginx-module#15]
I'm having severe difficulties which are likely my fault (I admit it up front), but the error message presented doesn't point to the proper resolution because it appears to be blank.
# Steps to reproduce
1. Create a Service Host Principal in Active Directory (2008)
2. Create a keytab for that SP
3. Transfer the keytab to the webserver
4. Configured KRB on the web server
5. Configure Nginx (built with the module support):

```
server {
... CONFIG HERE ...
auth_gss on;
auth_gss_keytab /PATH/TO/KEYTAB;
auth_gss_realm REALM.NAME.TLD;
auth_gss_service_name HTTP/hostname.name.tld;
}
```
1. Test: klist -k -t works (creates a tgt entry in klist)
2. Restart Nginx
3. Access the web server using Firefox or Chrome with SPNEGO configured (trusted-uris)
# Expected behavior

200 OK from server
# Actual result

403 Forbidden

Log file contains:

```
2014/06/18 10:25:20 [debug] 18085#0: *1 Client sent a reasonable Negotiate header
2014/06/18 10:25:20 [debug] 18085#0: *1 GSSAPI authorizing
2014/06/18 10:25:20 [debug] 18085#0: *1 Use keytab /usr/local/nginx/conf/hr.keytab
2014/06/18 10:25:20 [debug] 18085#0: *1 Using service principal: HTTP/host.name.tld@REALM.NAME.TLD
2014/06/18 10:25:20 [debug] 18085#0: *1 my_gss_name HTTP/host.name.tld@REALM.NAME.TLD
2014/06/18 10:25:20 [debug] 18085#0: *1 gss_accept_sec_context() failed: :
2014/06/18 10:25:20 [debug] 18085#0: *1 GSSAPI failed
2014/06/18 10:25:20 [debug] 18085#0: *1 http finalize request: 403, "/?" a:1, c:1
2014/06/18 10:25:20 [debug] 18085#0: *1 http special response: 403, "/?"
2014/06/18 10:25:20 [debug] 18085#0: *1 http set discard body
2014/06/18 10:25:20 [debug] 18085#0: *1 HTTP/1.1 403 Forbidden
```

As you can see, the gss_accept_sec_context() fails and it looks as though an error should appear, but there's nothing there.

Can you fix it to display the error returned by the kerberos libraries? Thanks.

**Comment by paulfertser** [comment]
Hello, @stnoonan. Was just beaten by inappropriate keytab permissions badly (didn't expect nginx uses user nobody even running on OpenWrt). Can you please consider checking keytab readability in the plugin itself as the blank error message from gssapi is highly confusing? Also, it'd be nice to see it even if nginx wasn't configured with --enable-debug.
