### ISSUE TITLE
Please add a Sample Configuration File to the Documentation

### ISSUE THREAD

**Issue by BenAHammond** [stnoonan/spnego-http-auth-nginx-module#29]
Currently the documentation lists some details on individual properties to set, but nothing on where or how to set them.

For Unix newbies like myself, this would be very helpful to have examples of.

**Comment by wildneuro** [comment]
Where could be a problem, if kinit on Linux works perfectly:

# kinit -5 -V -k -t /etc/krb5.keytab HTTP/nginx.sqedra.com@SQEDRA.COM                                                                                
Using default cache: /tmp/krb5cc_0
Using principal: HTTP/nginx.sqedra.com@SQEDRA.COM
Using keytab: /etc/krb5.keytab
Authenticated to Kerberos v5

, but browser auth (right from the Win2008r2 KDC, IE browser) lead to the error:

2015/04/21 07:48:20 [debug] 4819#0: *4 http header done
2015/04/21 07:48:20 [debug] 4819#0: *4 rewrite phase: 0
2015/04/21 07:48:20 [debug] 4819#0: *4 test location: "/"
2015/04/21 07:48:20 [debug] 4819#0: *4 using configuration "/"
2015/04/21 07:48:20 [debug] 4819#0: *4 http cl:-1 max:1048576
2015/04/21 07:48:20 [debug] 4819#0: *4 rewrite phase: 2
2015/04/21 07:48:20 [debug] 4819#0: *4 post rewrite phase: 3
2015/04/21 07:48:20 [debug] 4819#0: *4 generic phase: 4
2015/04/21 07:48:20 [debug] 4819#0: *4 generic phase: 5
2015/04/21 07:48:20 [debug] 4819#0: *4 access phase: 6
2015/04/21 07:48:20 [debug] 4819#0: *4 SSO auth handling IN: token.len=0, head=0, ret=401
2015/04/21 07:48:20 [debug] 4819#0: *4 Begin auth
2015/04/21 07:48:20 [debug] 4819#0: *4 Detect basic auth
2015/04/21 07:48:20 [debug] 4819#0: *4 Detect SPNEGO token
2015/04/21 07:48:20 [debug] 4819#0: *4 SSO auth handling OUT: token.len=0, head=1, ret=401
2015/04/21 07:48:20 [debug] 4819#0: *4 http finalize request: 401, "/?" a:1, c:1
2015/04/21 07:48:20 [debug] 4819#0: *4 http special response: 401, "/?"
2015/04/21 07:48:20 [debug] 4819#0: *4 http set discard body
2015/04/21 07:48:20 [debug] 4819#0: *4 posix_memalign: 0000000002304970:4096 @16
2015/04/21 07:48:20 [debug] 4819#0: *4 HTTP/1.1 401 Unauthorized

and slightly further by the log file:

2015/04/21 07:48:20 [debug] 4819#0: *4 http header done
2015/04/21 07:48:20 [debug] 4819#0: *4 rewrite phase: 0
2015/04/21 07:48:20 [debug] 4819#0: *4 test location: "/"
2015/04/21 07:48:20 [debug] 4819#0: *4 using configuration "/"
2015/04/21 07:48:20 [debug] 4819#0: *4 http cl:-1 max:1048576
2015/04/21 07:48:20 [debug] 4819#0: *4 rewrite phase: 2
2015/04/21 07:48:20 [debug] 4819#0: *4 post rewrite phase: 3
2015/04/21 07:48:20 [debug] 4819#0: *4 generic phase: 4
2015/04/21 07:48:20 [debug] 4819#0: *4 generic phase: 5
2015/04/21 07:48:20 [debug] 4819#0: *4 access phase: 6
2015/04/21 07:48:20 [debug] 4819#0: *4 SSO auth handling IN: token.len=0, head=0, ret=401
2015/04/21 07:48:20 [debug] 4819#0: *4 Begin auth
2015/04/21 07:48:20 [debug] 4819#0: *4 Detect basic auth
2015/04/21 07:48:20 [debug] 4819#0: *4 Detect SPNEGO token
2015/04/21 07:48:20 [debug] 4819#0: *4 posix_memalign: 00000000022F0420:4096 @16
2015/04/21 07:48:20 [debug] 4819#0: *4 Token decoded: SOMEBIGTEXT
2015/04/21 07:48:20 [debug] 4819#0: *4 Client sent a reasonable Negotiate header
2015/04/21 07:48:20 [debug] 4819#0: *4 GSSAPI authorizing
2015/04/21 07:48:20 [debug] 4819#0: *4 Use keytab /etc/krb5.keytab
2015/04/21 07:48:20 [debug] 4819#0: *4 gss_accept_sec_context() failed: :
2015/04/21 07:48:20 [debug] 4819#0: *4 GSSAPI failed
2015/04/21 07:48:20 [debug] 4819#0: *4 http finalize request: 403, "/?" a:1, c:1
2015/04/21 07:48:20 [debug] 4819#0: *4 http special response: 403, "/?"
2015/04/21 07:48:20 [debug] 4819#0: *4 http set discard body
2015/04/21 07:48:20 [debug] 4819#0: *4 HTTP/1.1 403 Forbidden

**Comment by wildneuro** [comment]
Ok, my problem solved. The issue was in time synchronization. Some how it just shifted by an hour (perhaps it's a timezone stuff). I just leave it here, in case someone will google it :)

Thanks
