### ISSUE TITLE
[Feature] Turn Off 401 Response

### ISSUE THREAD

**Issue by wells** [stnoonan/spnego-http-auth-nginx-module#30]
Would it be possible to have a failed SPNEGO get passed on to a web application (PHP/Ruby/etc) without returning a 401? That way I could have the web app handle the failure with it's own auth system, rather than spit back a 401 for those who don't have SPNEGO by default (i.e. Firefox). I've got the fallback to basic auth turned off. I think this feature would be very useful. What do you think @stnoonan

**Comment by wells** [comment]
Hang on. This is what I get in my debug log when no SPNEGO token is provided (using Firefox with no about:config alterations). It also doesn't seem to pass this 401 response or 403 response error on to php even when I specify a directive such as ```error_page 401 403 404 /index.php``` or a directive such as ```fastcgi_intercept_errors on;```

Debug log:
```
2015/01/05 09:19:07 [debug] 11961#0: *1 SSO auth handling IN: token.len=0, head=0, ret=401
2015/01/05 09:19:07 [debug] 11961#0: *1 Begin auth
2015/01/05 09:19:07 [debug] 11961#0: *1 Detect SPNEGO token
2015/01/05 09:19:07 [debug] 11961#0: *1 SSO auth handling OUT: token.len=0, head=1, ret=401
2015/01/05 09:19:07 [debug] 11961#0: *1 http finalize request: 401, "/?" a:1, c:1
2015/01/05 09:19:07 [debug] 11961#0: *1 http special response: 401, "/?"
2015/01/05 09:19:07 [debug] 11961#0: *1 http set discard body
2015/01/05 09:19:07 [debug] 11961#0: *1 xslt filter header
2015/01/05 09:19:07 [debug] 11961#0: *1 charset: "" > "utf-8"
2015/01/05 09:19:07 [debug] 11961#0: *1 HTTP/1.1 401 Unauthorized
```

Config is:
```
auth_gss on;
auth_gss_keytab /etc/nginx/conf.d/sample.keytab;
auth_gss_allow_basic_fallback off;
```

**Comment by harbirg** [comment]
@wells Did you find a graceful method to handle failed spengo negotiation attempt via a login form on your app instead of using basic auth?
