### ISSUE TITLE
Authorization: Negotiate fails on windows

### ISSUE THREAD

**Issue by gintsmurans** [stnoonan/spnego-http-auth-nginx-module#31]
Hi! I am trying to get spnego fallback working on windows when there is no domain login. Currently everything works as it should, by everything I mean user can login using chrome on OSX, it also works when user is logged on the domain in windows, but it somehow fails when user hasn't been logged in by domain user and Chrome and IE chooses to use Authorization: Negotiate. 

Here is a part of debug log:

    2015/01/12 21:09:17 [debug] 5499#0: *28 Begin auth
    2015/01/12 21:09:17 [debug] 5499#0: *28 Detect basic auth
    2015/01/12 21:09:17 [debug] 5499#0: *28 Detect SPNEGO token
    2015/01/12 21:09:17 [debug] 5499#0: *28 Token decoded: TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGA4AlAAAADw==
    2015/01/12 21:09:17 [debug] 5499#0: *28 Client sent a reasonable Negotiate header
    2015/01/12 21:09:17 [debug] 5499#0: *28 GSSAPI authorizing
    2015/01/12 21:09:17 [debug] 5499#0: *28 Use keytab /etc/nginx/global/http_ad.keytab
    2015/01/12 21:09:17 [debug] 5499#0: *28 gss_accept_sec_context() failed: Unknown error:
    2015/01/12 21:09:17 [debug] 5499#0: *28 GSSAPI failed

Btw, this is really great module, thanks for making it.

**Comment by stnoonan** [comment]
What do you mean by "but it somehow fails when user hasn't been logged in by domain user?"
Do they have kerberos credentials, but they have expired?

**Comment by gintsmurans** [comment]
No, what I meant is - they are logged on locally, not in domain. In this case it should fall back to basic auth, right? But browser chooses to use Negotiate stuff and on server I get that error. It works just fine on OSX, though.

**Comment by stnoonan** [comment]
That really sounds like a browser bug or browser config issue.  If your client doesn't have credentials, it shouldn't have anything to send...

**Comment by gintsmurans** [comment]
Hi,

I finally had a chance to play with this again and I think I have found the issue. Turns out it was actually Negotiate auth that was asking for a username and password and if I specify only username without domain name (realm), then it won't work, but it would work if I specify full username@domain.name. 

A quick look on the code tells me that it is not, but just to confirm it, is there any way to tell spnego to use default realm if there is none in the header? Same as basic auth fallback seems to be doing.

**Comment by stnoonan** [comment]
From the readme:
auth_gss_realm: Kerberos realm name. If this is specified, the realm is only passed to the nginx variable $remote_user if it differs from this default. To override this behavior, set auth_gss_format_full to 1 in your configuration.

IIRC (I haven't looked), if you set auth_gss_realm, we'll append it to naked usernames.
