### ISSUE TITLE
error_page 401 semantics

### ISSUE THREAD

**Issue by oranki** [stnoonan/spnego-http-auth-nginx-module#32]
Problem: Using a custom 401 page doesn't work. Nginx catches the first 401, which is part of SPNEGO protocol, so client never gets to even try authentication.

Solution 1: Only use error_page 401 after all available auth methods are exhausted. This is what Apache/mod_auth_kerb does, AFAIK.

Solution 2: Return 403 instead of 401 when auth has failed.

I'd like to setup following logic:
- SPNEGO on plaintext HTTP, basic fallback disabled
- If it fails, automatic redirect to HTTPS
- SPNEGO on HTTPS, basic fallback enabled

**Comment by stnoonan** [comment]
We already do return a 403 when auth is attempted but fails.  If you prefer the behavior of Apache/mod_auth_kerb and it meets your needs, I'm not sure why you would switch :- ).

If you have a patch that adds the behavior you'd like to see, please submit a pull request and we can discuss it there.

**Comment by oranki** [comment]
A 401 is returned at least for clients using Linux/Chrome when no Kerberos ticket is initialized.

Why not use Apache? Nginx is multiple times faster, which becomes very relevant over high-latency links. The problem with 401/403 responses is anyway a minor thing.

**Comment by oranki** [comment]
This might actually be a client-side problem. I'll investigate.
