### ISSUE TITLE
Support for ticket delegation

### ISSUE THREAD

**Issue by oranki** [stnoonan/spnego-http-auth-nginx-module#33]
Are there plans to support ticket delegation?

**Comment by oranki** [comment]
It seems like nowadays requirement would be supporting both traditional TGT forwarding and Microsoft's "constrained delegation" extension, S4U2Proxy: https://msdn.microsoft.com/en-us/library/cc246071.aspx

MIT Kerberos and Apache mod_auth_kerb support both, so there's a reference implementation available.

**Comment by stnoonan** [comment]
Personally, I don't have any use for this, but would accept a pull request.

**Comment by oranki** [comment]
I'll take a look what it would require to port support from mod_auth_kerb.

**Comment by adfel70** [comment]
Hi, I though this issue opened time ago, we could really use it these days. Any chance it would be implemented? :pray:

**Comment by dx44** [comment]
@adfel70 , see PR #105 . I'm waiting too that's be validated and merged.

**Comment by ABOB069** [comment]
HI, will this be merged please?

**Comment by stnoonan** [comment]
The PR was merged.
