### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by merlin-tc** [stnoonan/spnego-http-auth-nginx-module#34]
Do you have a timeframe on when the next version is going to be tagged?
It would make packaging for a distribution a lot easier, internally we use the latest git snapshot to build against nginx since 1.0.0 doesn't contain all the necessary features.

**Comment by stnoonan** [comment]
I suppose I'll cut a new one soon.

**Comment by stnoonan** [comment]
@merlin-tc - let me know if you're happy with the current git tip.  If so, I'll cut a new release there.

**Comment by merlin-tc** [comment]
@stnoonan - yes, I'd be very happy! thanks!

**Comment by stnoonan** [comment]
Any chance you tested the current git tip?

**Comment by merlin-tc** [comment]
@stnoonan - Sorry for the late response.
I just did a checkout (commit c85a38c595c6f45609f9984c3254a33996ed587d) and built it against nginx version 1.8.1
It works without any problems.
A new tag here on github with a proper version number would be great so I don't have to make up any imaginary version numbers internally.

Thanks a lot.

**Comment by stnoonan** [comment]
Tagged v1.1.0
