### ISSUE TITLE
SLES 11 Install

### ISSUE THREAD

**Issue by fkhoury** [stnoonan/spnego-http-auth-nginx-module#35]
Is it possible you can tell me what I need to install on SLES 11 SP2? I keep running into com_err.h file or folder cant be found. I am missing something. I keep trying to match items up between the distros but figured I would just ask you. thanks

**Comment by stnoonan** [comment]
Probably libcom_err-devel, but it will put it into /usr/include/et/com_err.h.  You might need to add -I/usr/include/et to CFLAGS, but I am not sure.  Reopen if none of that works.
