### ISSUE TITLE
Purpose of ngx_http_auth_spnego_set_bogus_authorization

### ISSUE THREAD

**Issue by tkdchen** [stnoonan/spnego-http-auth-nginx-module#38]
Does calling this function `ngx_http_auth_spnego_set_bogus_authorization` aims to cause nginx to add REMOTE_USER in the HTTP request headers automatically on behalf of `spnego-http-auth-nginx-module` itself, just as a standard HTTP Basic authentication just happened?

**Comment by stnoonan** [comment]
No, it does not set the header.  It sets the nginx variable $remote_user, which you can use to set the header.  It does set a bogus "Authorization" header, which is passed to your backend.

I don't like this behavior and have considered changing it (I inherited it from the non-working module).  Only $remote_user is reserved for basic auth, so I think we could change the code to set $spnego_user.  It hasn't been a high priority.

**Comment by tkdchen** [comment]
A further question is, why have to set a bogus "Authorization" header when authenticating in GSSAPI? Actually, the application, which is behind nginx, does not need to care about this header usually. At least, in my previous and current applications (Django + Apache + mod_auth_kerb), no one needs to check Authorization header, in the contrast, only `REMOTE_USER` is necessary for the Web framework and its authentication backend.

I'm working on projects acrossing `Apache + mod_auth_kerb + Django` and `nginx + spnego-http-auth-nginx-module + nodejs`. The difference behavior between them, the way of handling `REMOTE_USER`, makes me a little bit confused.

If I understand correctly, my problem can be solved by setting nginx' variable `$remote_user` to `REMOTE_USER` manually in conf. In this way, whichever the way is chose to authenticate client, via Basic authentication (fallback mode) or GSSAPI, that header will appear in the HTTP request eventually passed to the application. Am I right?

Thanks for your quick response.

**Comment by stnoonan** [comment]
The authorization header is a side effect of the basic auth call.  See the
documentation for a way to prevent it being shown to your application.
