### ISSUE TITLE
gss_acquire_cred() failed: Permission denied

### ISSUE THREAD

**Issue by wildneuro** [stnoonan/spnego-http-auth-nginx-module#39]
Hi, all settings done right, but I'm still getting this error:

2015/04/21 01:07:04 [debug] 3603#0: *66 Client sent a reasonable Negotiate header
2015/04/21 01:07:04 [debug] 3603#0: *66 GSSAPI authorizing
2015/04/21 01:07:04 [debug] 3603#0: *66 Use keytab /etc/krb5.keytab
2015/04/21 01:07:04 [debug] 3603#0: *66 Using service principal: HTTP/nginx.sqedra.com@SQEDRA.COM
2015/04/21 01:07:04 [debug] 3603#0: *66 my_gss_name HTTP/nginx.sqedra.com@SQEDRA.COM
2015/04/21 01:07:04 [error] 3603#0: *66 gss_acquire_cred() failed: Permission denied: Used service principal: HTTP/nginx.sqedra.com@SQEDRA.COM, client: 10.0.55.141, server: nginx.sqedra.com, request: "GET / HTTP/1.1", host: "nginx.sqedra.com"
2015/04/21 01:07:04 [debug] 3603#0: *66 GSSAPI failed
2015/04/21 01:07:04 [debug] 3603#0: *66 http finalize request: 500, "/?" a:1, c:1
2015/04/21 01:07:04 [debug] 3603#0: *66 http special response: 500, "/?"
2015/04/21 01:07:04 [debug] 3603#0: *66 http set discard body
2015/04/21 01:07:04 [debug] 3603#0: *66 HTTP/1.1 500 Internal Server Error
Server: nginx/1.7.12
Date: Mon, 20 Apr 2015 22:07:04 GMT
Content-Type: text/html
Content-Length: 193
Connection: close

**Comment by stnoonan** [comment]
What user is nginx dropping privs to and does that user have read and write
access to the keytab?

**Comment by wildneuro** [comment]
Thanks for the fast answer, user is root, keytab is 777 (just for testing still)

**Comment by wildneuro** [comment]
By mistake, previous error was somewhat www-data user, and after I changed it to root, here what we have:

2015/04/21 01:24:04 [debug] 3616#0: *3 Client sent a reasonable Negotiate header
2015/04/21 01:24:04 [debug] 3616#0: *3 GSSAPI authorizing
2015/04/21 01:24:04 [debug] 3616#0: *3 Use keytab /etc/krb5.keytab
2015/04/21 01:24:04 [debug] 3616#0: *3 Using service principal: HTTP/nginx.sqedra.com@SQEDRA.COM
2015/04/21 01:24:04 [debug] 3616#0: *3 my_gss_name HTTP/nginx.sqedra.com@SQEDRA.COM
2015/04/21 01:24:04 [debug] 3616#0: *3 gss_accept_sec_context() failed: :
2015/04/21 01:24:04 [debug] 3616#0: *3 GSSAPI failed
2015/04/21 01:24:04 [debug] 3616#0: *3 http finalize request: 403, "/?" a:1, c:1
2015/04/21 01:24:04 [debug] 3616#0: *3 http special response: 403, "/?"
2015/04/21 01:24:04 [debug] 3616#0: *3 http set discard body
2015/04/21 01:24:04 [debug] 3616#0: *3 HTTP/1.1 403 Forbidden
Server: nginx/1.7.12
Date: Mon, 20 Apr 2015 22:24:04 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive

**Comment by stnoonan** [comment]
Can you share your relevant config sections?

**Comment by wildneuro** [comment]
Sure, I'll post all conf:


user  root;
worker_processes  1;

# error_log  logs/error.log;
# error_log  logs/error.log  notice;
error_log  logs/error.log  debug;

# pid        /var/lock/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    # server {
    #     listen       80;
    #     server_name  localhost;

    #     #charset koi8-r;

    #     access_log  logs/host.access.log  main;

    #     location / {
    #         root   html;
    #         index  index.html index.htm;
    #     }

    #     #error_page  404              /404.html;

    #     # redirect server error pages to the static page /50x.html
    #     #
    #     error_page   500 502 503 504  /50x.html;
    #     location = /50x.html {
    #         root   html;
    #     }

    #     # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #     #
    #     #location ~ \.php$ {
    #     #    proxy_pass   http://127.0.0.1;
    #     #}

    #     # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #     #
    #     #location ~ \.php$ {
    #     #    root           html;
    #     #    fastcgi_pass   127.0.0.1:9000;
    #     #    fastcgi_index  index.php;
    #     #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #     #    include        fastcgi_params;
    #     #}

    #     # deny access to .htaccess files, if Apache's document root
    #     # concurs with nginx's one
    #     #
    #     #location ~ /\.ht {
    #     #    deny  all;
    #     #}
    # }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    server {
       listen       443 ssl;
       server_name  nginx.sqedra.com;

       ssl_certificate      /usr/local/nginx/ssl/server.crt;
       ssl_certificate_key  /usr/local/nginx/ssl/server.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       location / {
           root   html;
           index  index.html index.htm;
           auth_gss on;
           auth_gss_realm SQEDRA.COM;
           auth_gss_keytab /etc/krb5.keytab;
           auth_gss_service_name HTTP/nginx.sqedra.com;
       }
    }

}

**Comment by stnoonan** [comment]
Try without auth_gss_realm and auth_gss_service_name ?

**Comment by wildneuro** [comment]
Tryed, still the same. Here is some new data from other browser (not IE, chrome 40):

2015/04/21 01:46:39 [debug] 1152#0: *12 write new buf t:1 f:0 000000000238A890, pos 000000000238A890, size: 221 file: 0, size: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 http write filter: l:0 f:0 s:221
2015/04/21 01:46:39 [debug] 1152#0: *12 http output filter "/favicon.ico?"
2015/04/21 01:46:39 [debug] 1152#0: *12 http copy filter: "/favicon.ico?"
2015/04/21 01:46:39 [debug] 1152#0: *12 http postpone filter "/favicon.ico?" 000000000238F3D0
2015/04/21 01:46:39 [debug] 1152#0: *12 write old buf t:1 f:0 000000000238A890, pos 000000000238A890, size: 221 file: 0, size: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 write new buf t:0 f:0 0000000000000000, pos 00000000006AD1E0, size: 142 file: 0, size: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 write new buf t:0 f:0 0000000000000000, pos 00000000006AD780, size: 53 file: 0, size: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 write new buf t:0 f:0 0000000000000000, pos 00000000006AD5A0, size: 402 file: 0, size: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 http write filter: l:1 f:0 s:818
2015/04/21 01:46:39 [debug] 1152#0: *12 http write filter limit 0
2015/04/21 01:46:39 [debug] 1152#0: *12 malloc: 000000000236F5E0:16384
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL buf copy: 221
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL buf copy: 142
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL buf copy: 53
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL buf copy: 402
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL to write: 818
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL_write: 818
2015/04/21 01:46:39 [debug] 1152#0: *12 http write filter 0000000000000000
2015/04/21 01:46:39 [debug] 1152#0: *12 http copy filter: 0 "/favicon.ico?"
2015/04/21 01:46:39 [debug] 1152#0: *12 http finalize request: 0, "/favicon.ico?" a:1, c:1
2015/04/21 01:46:39 [debug] 1152#0: *12 set http keepalive handler
2015/04/21 01:46:39 [debug] 1152#0: *12 http close request
2015/04/21 01:46:39 [debug] 1152#0: *12 http log handler
2015/04/21 01:46:39 [debug] 1152#0: *12 free: 000000000238E410, unused: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 free: 000000000238A870, unused: 3190
2015/04/21 01:46:39 [debug] 1152#0: *12 free: 00000000023AA840
2015/04/21 01:46:39 [debug] 1152#0: *12 hc free: 0000000000000000 0
2015/04/21 01:46:39 [debug] 1152#0: *12 hc busy: 0000000000000000 0
2015/04/21 01:46:39 [debug] 1152#0: *12 free: 000000000236F5E0
2015/04/21 01:46:39 [debug] 1152#0: *12 reusable connection: 1
2015/04/21 01:46:39 [debug] 1152#0: *12 event timer add: 4: 65000:1429570064911
2015/04/21 01:46:39 [debug] 1152#0: timer delta: 43
2015/04/21 01:46:39 [debug] 1152#0: worker cycle
2015/04/21 01:46:39 [debug] 1152#0: epoll timer: 65000
2015/04/21 01:46:39 [debug] 1152#0: epoll: fd:4 ev:0001 d:00007F39468AA1C0
2015/04/21 01:46:39 [debug] 1152#0: *12 http keepalive handler
2015/04/21 01:46:39 [debug] 1152#0: *12 malloc: 00000000023AA840:1024
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL_read: 423
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL_read: -1
2015/04/21 01:46:39 [debug] 1152#0: *12 SSL_get_error: 2
2015/04/21 01:46:39 [debug] 1152#0: *12 reusable connection: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 posix_memalign: 000000000238E410:4096 @16
2015/04/21 01:46:39 [debug] 1152#0: *12 event timer del: 4: 1429570064911
2015/04/21 01:46:39 [debug] 1152#0: *12 http process request line
2015/04/21 01:46:39 [debug] 1152#0: *12 http request line: "GET /favicon.ico HTTP/1.1"
2015/04/21 01:46:39 [debug] 1152#0: *12 http uri: "/favicon.ico"
2015/04/21 01:46:39 [debug] 1152#0: *12 http args: ""
2015/04/21 01:46:39 [debug] 1152#0: *12 http exten: "ico"
2015/04/21 01:46:39 [debug] 1152#0: *12 http process request header line
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Host: nginx.sqedra.com"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Connection: keep-alive"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Authorization: Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw=="
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Accept: */*"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Referer: https://nginx.sqedra.com/"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Accept-Encoding: gzip, deflate, sdch"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header: "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"
2015/04/21 01:46:39 [debug] 1152#0: *12 http header done
2015/04/21 01:46:39 [debug] 1152#0: *12 rewrite phase: 0
2015/04/21 01:46:39 [debug] 1152#0: *12 test location: "/"
2015/04/21 01:46:39 [debug] 1152#0: *12 using configuration "/"
2015/04/21 01:46:39 [debug] 1152#0: *12 http cl:-1 max:1048576
2015/04/21 01:46:39 [debug] 1152#0: *12 rewrite phase: 2
2015/04/21 01:46:39 [debug] 1152#0: *12 post rewrite phase: 3
2015/04/21 01:46:39 [debug] 1152#0: *12 generic phase: 4
2015/04/21 01:46:39 [debug] 1152#0: *12 generic phase: 5
2015/04/21 01:46:39 [debug] 1152#0: *12 access phase: 6
2015/04/21 01:46:39 [debug] 1152#0: *12 SSO auth handling IN: token.len=0, head=0, ret=401
2015/04/21 01:46:39 [debug] 1152#0: *12 Begin auth
2015/04/21 01:46:39 [debug] 1152#0: *12 Detect basic auth
2015/04/21 01:46:39 [debug] 1152#0: *12 Detect SPNEGO token
2015/04/21 01:46:39 [debug] 1152#0: *12 Token decoded: TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==
2015/04/21 01:46:39 [debug] 1152#0: *12 Client sent a reasonable Negotiate header
2015/04/21 01:46:39 [debug] 1152#0: *12 GSSAPI authorizing
2015/04/21 01:46:39 [debug] 1152#0: *12 Use keytab /etc/krb5.keytab
2015/04/21 01:46:39 [debug] 1152#0: *12 Using service principal: HTTP/nginx.sqedra.com@
2015/04/21 01:46:39 [debug] 1152#0: *12 my_gss_name HTTP/nginx.sqedra.com@
2015/04/21 01:46:39 [debug] 1152#0: *12 posix_memalign: 00000000023942E0:4096 @16
2015/04/21 01:46:39 [debug] 1152#0: *12 gss_accept_sec_context() failed: Unknown error:
2015/04/21 01:46:39 [debug] 1152#0: *12 GSSAPI failed
2015/04/21 01:46:39 [debug] 1152#0: *12 http finalize request: 403, "/favicon.ico?" a:1, c:1
2015/04/21 01:46:39 [debug] 1152#0: *12 http special response: 403, "/favicon.ico?"
2015/04/21 01:46:39 [debug] 1152#0: *12 http set discard body
2015/04/21 01:46:39 [debug] 1152#0: *12 HTTP/1.1 403 Forbidden
Server: nginx/1.7.12
Date: Mon, 20 Apr 2015 22:46:39 GMT
Content-Type: text/html
Content-Length: 571
Connection: keep-alive

**Comment by stnoonan** [comment]
Can you show the output of klist -k?  That is, the contents of the keytab.

**Comment by wildneuro** [comment]
Sure,

*# klist -k*
Keytab name: FILE:/etc/krb5.keytab
KVNO Principal
----
--------------------------------------------------------------------------
   6 host/nginx.sqedra.com@SQEDRA.COM
   7 HTTP/nginx.sqedra.com@SQEDRA.COM

*# ll /etc/krb5.keytab *
-rwxrwxrwx 1 root root 144 Apr 21 00:48 /etc/krb5.keytab*


--
signed by Victor Brunko

**Comment by wildneuro** [comment]
By the way:

*# kinit -5 -V -k -t /etc/krb5.keytab HTTP/nginx.sqedra.com@SQEDRA.COM
<nginx.sqedra.com@SQEDRA.COM>*
Using default cache: /tmp/krb5cc_0
Using principal: HTTP/nginx.sqedra.com@SQEDRA.COM
Using keytab: /etc/krb5.keytab
Authenticated to Kerberos v5


--
signed by Victor Brunko

**Comment by stnoonan** [comment]
Your client is sending NTLMSSP, not GSSAPI.

⇒  echo TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw== | base64 -d
NTLMSSP���%

**Comment by wildneuro** [comment]
OMG, thanks a lot. So, seems to me it's all browser stuff. But why...
strange...

--
signed by Victor Brunko

**Comment by wildneuro** [comment]
Issue is closed. First of all browser tries to auth with GSSAPI, if it's failed it tries to use tries to use NTLMSSP. In my case, it was all about. Thanks for point out.

**Comment by LiSinCin** [comment]
very helpful thread. tnx @wildneuro

**Comment by chaddotson** [comment]
@wildneuro what was causing the browser to use ntlm?

**Comment by wildneuro** [comment]
@chaddotson it's was a standalone project where they wanted to use NTLM

**Comment by chaddotson** [comment]
Ah roger that.  Thanks for the response!  I filed another issue here about what all scenarios could lead to a permission denied so I was wondering.

**Comment by arturslogins** [comment]
Hello, i have the same issue 
echo TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAGFKAAAADw== | base64 -d
NTLMSSP▒▒


What is solution for this issue?

**Comment by chaddotson** [comment]
> Hello, i have the same issue echo TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAGFKAAAADw== | base64 -d NTLMSSP▒▒
> 
> What is solution for this issue?

Your browser is sending NTLMSSP which isn't supported by this module.  As others have mentioned, GSSAPI may have failed and the browser tried NTLMSSP as a fallback.  I suggest checking logs above the NTLMSSP failure to confirm.
