### ISSUE TITLE
Avoid 401 Round Trip

### ISSUE THREAD

**Issue by AaronOpfer** [stnoonan/spnego-http-auth-nginx-module#42]
Hello,

I've been using this module in my DEV & QA environments and recently started rolling out to production as a part of my campaign to replace apache2 and it's working great so far, very pleased with this module overall.

I noticed in the logs, however, a pattern of an anonymous GET that returns 401 occurring before every (authenticated) request. Even though we're on a fast LAN network this seems wasteful. I'd like to reduce this if possible.

Apparently IIS has an option for reducing these roundtrips: http://blogs.msdn.com/b/saurabh_singh/archive/2010/01/06/case-study-are-you-seeing-401-s-too-often-for-http-web-requests.aspx

Is it possible for this module to do something similar? Although I am not sure how that option works under the hood. It sounds like Chrome is behaving correctly according to the spec to make sure the server wants authentication on every request. But maybe this module could store a mapping of client connections to authenticated usernames in order to avoid the repeat requests, so that anonymous requests on a previously authenticated connection don't need to make another 401 roundtrip?

Thanks.

**Comment by AaronOpfer** [comment]
So I gave this more thought and then realized that this is probably not done because of load balancers / proxies / etc keeping a persistent connection to the nginx server with the SPNEGO plugin that represent several clients at once. Obviously keeping authentication for that whole connection would result in incorrect authentication being used for a repeat request.

So I'm not sure if this is a fixable thing. In our situation we have no additional load balancers in front of our authorization server running this plugin so I would be quite happy with this persistent-auth-for-connection option that has lots and lots of "please don't do this" warnings on it.

**Comment by stnoonan** [comment]
One way to do this is to set a cookie in your application and not redirect to an auth endpoint if the cookie is set.  It requires some additional work on your part and a more complicated nginx config, but is better than it being implemented here.

**Comment by AaronOpfer** [comment]
Yeah, this is something we had considered but right now our apps are entirely stateless and making them handle cookies securely (opaque, not vulnerable to replay attacks, etc) and stateless (no db) sounds pretty difficult.

But, if I did come up with a solution for the cookie, it looks like everything else would "just work" if we did /endpoint 307redir-> /login 307redir-> /endpoint loop in the application, which would turn into something like POST /endpoint -> 307 Moved /login -> 401 Challenge -> 307 Moved -> /endpoint if the user logs in successfully. (307 redirects keep POST body http://programmers.stackexchange.com/a/99966)

**Comment by stnoonan** [comment]
Yeah, I appreciate that this is painful, but it is how SPNEGO works.  If you don't want to do spnego auth each time, that's an application level config.  My personal feeling is that this module is complicated enough as it is, especially since there isn't a single test with it - I'd prefer not to add more features if we can avoid it.
