### ISSUE TITLE
Should support Basic fallback if client-offered negotiate mechanism is not supported

### ISSUE THREAD

**Issue by AaronOpfer** [stnoonan/spnego-http-auth-nginx-module#44]
So I managed to finally track this down by comparing the behavior of an apache2 instance compared to nginx with this module:

In Apache2 land, when a client accepts the WWW-Authenticate: negotiate mechanism but offers  an unsupported protocol, like NTLMSSP, apache2 returns 401 and then gives WWW-Authenticate: Basic realm="foo"  as the ONLY option. User-Agents are then observed using the basic fallback, prompting users for a password, and once the user provides the password, the users are able to access the site.

However, this module has been observed returning 403 Forbidden when an unsupported negotiate mechanism is offered (such as NTLMSSP). This results in the user-agent immediately caching the credentials and then all further requests to the website immediately return 403 Forbidden. Technically this is in-spec: 403 Forbidden says that the credentials are correct, but don't have access.

I believe that the module should be more accommodating to clients offering poor negotiation mechanisms by performing the same behavior: dropping the negotiate header when clients cannot or will not use kerberos.

**Comment by stnoonan** [comment]
Since you phrased it that way - I don't share your belief.  In fact, I don't even think basic fallback should be an option here.  However, some people find it useful.  I'd be happy to consider/review a pull request, but I don't consider this a bug.
