### ISSUE TITLE
Nginx as a Kerberos Client?

### ISSUE THREAD

**Issue by mekuiper** [stnoonan/spnego-http-auth-nginx-module#45]
I am relatively new to Kerberos and Nginx.  I have a web application running with the browser configured to add the Kerberos ticket to the Authorization header.  I have verified the Kerberos ticket going into my Nginx reverse proxy matches the header in the request leaving the proxy, but I am getting a Kerberos related error when the request hits the Kerberos protected resource.  The company that creates the protected protected has stated that under the current version the do not support a Kerberos client from behind a proxy...

So that is the background.  I am wondering if this Github project would be a solution, but I do not understand what this nginx module does.  Could you explain more?  I have thought that if the Nginx reverse proxy could become a Kerberos client and request a ticket from the KDC, then this might solve my problem.  This module support Nginx being a Kerberos client?

Thanks,
Matt

**Comment by stnoonan** [comment]
This module authenticates clients.  It does not support being a client itself.

**Comment by hunteratonoud** [comment]
Any updates on this since then ?

**Comment by pantaoran** [comment]
@stnoonan So you're saying that clients connecting to this nginx module still need to have their own keytab/credentials and still need to perform SPNEGO, albeit through nginx? Then why does this module need its own keytab specified? Why do I need this module at all? I'm genuinely trying to understand.

**Comment by martvaha** [comment]
This module supports authenticating clients via Kerberos. If you have another service behind your Nginx server you could use this module to authenticate your users and then pass on the username to that service by setting a header. For example:

```
location /protected {
	proxy_pass		http://HOST:PORT;
	proxy_set_header	REMOTE_USER $remote_user;
	auth_gss		on;
	auth_gss_keytab		/path/to/keytab/site.keytab;
	auth_gss_realm		REALM_TO_USE;
	auth_gss_force_realm	on;
}
```

If you want to know more about Kerberos authentication, I suggest you read this article: http://www.roguelynn.com/words/explain-like-im-5-kerberos/

**Comment by pantaoran** [comment]
Thanks for your reply.

So then this module is the opposite of what I'm looking for: it wraps an unprotected webserver and adds Krb Auth so that clients need to use Kerberos.

What I was looking for is a proxy that enables a client which does not understand Kerberos to authenticate against a Kerberized webserver.

**Comment by jasonkoo** [comment]
@pantaoran  Have you found any proxy that could serve as a kerberos client? I am also working on this.

**Comment by pantaoran** [comment]
> @pantaoran Have you found any proxy that could serve as a kerberos client? I am also working on this.

I think I managed to hack something with squid back then, but it's been a while...
