### ISSUE TITLE
enable/disable auth_gss depending on a request header 

### ISSUE THREAD

**Issue by douardda** [stnoonan/spnego-http-auth-nginx-module#46]
Note: I'm quite new on nginx config...

Hi,

I'm trying to set up a configuration in which gss auth can be disabled  if some request header is present (typically for cookie-based authentication).

I've tried something like:

auth_gss on;
 if ($http_authorization ~ (^MyStuff) ) {
     auth_gss off;
}

but it fails stating that "nginx: [emerg] "auth_gss" directive is not allowed here" 

Is there a way of doing something like this? 
Should I try to use auth_request? 

PS : with Apache, I used to do something like:

```
<Location />
AuthType kerberos
[...]
SetEnvIf Authorization "^MyStuff" signed
  <RequireAny>  
    Require env signed
    Require valid-user
  </RequireAny>
</Location>
```

**Comment by douardda** [comment]
What I have done so far:

```
server {
auth_gss on;
# ...
location /app1/ {
  satisfy any;
  auth_request /sr/;
  proxy_pass  http://xxx/;
}

location /sr/ {
  auth_gss off;
  if ($http_authorization ~ "^Mystuff") {
     return 200;
     }
     return 403;
  }
}
```

Not sure it's the best way of doing it, but it works.

**Comment by stnoonan** [comment]
Looks like you found a solution that works for you.
