### ISSUE TITLE
after set auth_gss on;  nginx return 403 Forbidden

### ISSUE THREAD

**Issue by Gman1988** [stnoonan/spnego-http-auth-nginx-module#51]
Hi i created server with this nginx module, and everything worked fine until somehow i started to get 403 Forbidden from my site.

I configured nginx with --with-debug parameter and added logs to the nginx.conf  but they didnt return any error, tehy all setted for debug lvl.

I checked permission to krb5.conf and krb5.keytab file, permission for whole files in nginx and i dont have clue.

Can anybody help ?

**Comment by stnoonan** [comment]
Do you have kerberos credentials on your client?  Have you tested with curl or a client other than a browser?  Do you have any logs to share?

**Comment by Gman1988** [comment]
Yeas i have kerberos credentials on client. What is more weird SSO worked fine i about 10 min.

Then i rebooted machine to check if it will work after reboot and it started to give me 403 error.

Access Log when it worked:

192.168.8.253 - pawel.glica [14/Jul/2015:15:05:48 +0200] "GET /?page_id=15 HTTP/1.1" 200 14353 "http://plhqkafeteria01/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36"


Access Log when it stopt:

192.168.8.253 - - [14/Jul/2015:15:24:36 +0200] "GET /?page_id=15 HTTP/1.1" 401 596 "http://plhqkafexxxxx/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36"

Host log:
2015/07/14 16:39:57 [info] 6159#0: *112 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 192.168.8.253, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "plhqkafexxxxx"

My nginx.conf
user  nginx;
worker_processes  4;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
  root   html;
        index  index.php index.html index.htm;


        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;

            auth_gss on;
            auth_gss_keytab /etc/krb5.keytab;
            auth_gss_realm MYDOMAIN.AD;
            auth_gss_service_name HTTP/myhost.amrest.ad;
            auth_gss_format_full off;

        }
}

MYDOMAIN and myhost are correct in my config i changed it for security reason ;]

Wget return error 401 unautorized on the machine.

**Comment by stnoonan** [comment]
wget does not perform spnego.  The 401 is a request to perform this negotiation.  You can try with

    curl -u: --negotiate <url>

Those logs are incomplete and not debug logs.  Is there any reason in particular that you are specifying auth_gss_service_name?  Have you verified that your keytab has HTTP/myhost.amrest.ad in it?

**Comment by Gman1988** [comment]
Answear from curl:

<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.9.2</center>
</body>
</html>

**Comment by stnoonan** [comment]
If you want to provide curl output, please use -v and show the entire
command line.

**Comment by Gman1988** [comment]
Hi i used curl from windows with credentails here is the output:

* Connected to plhqkafeteria01 (192.168.4.93) port 80 (#0)
* Adding handle: conn: 0x10e3c70
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x10e3c70) send_pipe: 1, recv_pipe: 0
* Server auth using GSS-Negotiate with user ''
> GET / HTTP/1.1
> Authorization: Negotiate YIIIVQYGKwYBBQUCoIIISTCCCEWgMDAuBgkqhkiC9xIBAgIGCSqGS
Ib3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCCA8EgggLYIIIBwYJKoZIhvcSAQICAQBuggf2M
IIH8qADAgEFoQMCAQ6iBwMFACAAAACjggaDYYIGfzCCBnugAwIBBaELGwlBTVJFU1QuQUSiIjAgoAMCA
QKhGTAXGwRIVFRQGw9wbGhxa2FmZXRlcmlhMDGjggZBMIIGPaADAgESoQMCAQKiggYvBIIGK6+/95J/j
UimlcaKPWSbNnRMo3b+4lrhwKfWxQ7dJ1Dr49b9BWuHrqynkClrhD4m1u8TqgrFGIuJwll1mrIwzDKJU
evtCaNakYW0TxDA4CMHvgdPL/IrTyW7DqKfYOYKazSKYoeK0Jfsm++OkhFh49N6D/+Xqi4mE3Ul62K27
2vKsaqgcITxxdWtGWephdnWy58WmRGEaWpOTk/+werL2k0vt7vMpH+1UjWSBUZqK230glrcvYyfjlVVh
ZBZSpJwweZHXidmhFaoMN7zW/sHpFbYO2FyAbey4yroqDqBUpM9ZBtwuOjdr63u21WhCiMNJB8NUbsHU
MYqdqAZ0bsTwB8Qxt8Za55yfhESB0ZWa2T3rU7SfX8GAM1lV5dvHN8b/CficvfTGPOEoFeRbhzDKUAVA
5/sC5DD7k02pBhPYRjwJvFmXyyvECpMRWp1xVDxEniHJLSf5U+VXWHmo6wZOQ4zSBEioL0a08gvHbK5N
8CoM1JKCNpCbgcuQBNc8j3mm/JpQyKAeL2Wz4Eygwkw0+XZPzH1JalKhGi9RPznsVM+XPPuPDFoauuxD
ycfV25tXtafss8Ylvlr5yBjEhMralVfM2YJCJcjslYosa0a2pkZy0P7oSHybX0rBMBXAryRohszHABAc
OnrAZg0IuESa5Fs0fv7ZHATPLPYl6Bm0sAU29yz2ADAF99b/pB+xwY/Zzpn9CWXf55lrqFK7rzWh+zZv
+/CceQtot1gM9EoVJlXrmT0C0NlBFahX9uXG8A7cTXHkJlpxO3Qq8o92weCDVlQMCwOdIZBCAWknwIXV
ct/7jy94FDlZoL6Z3uel8ySNQlgOuhHbBl51MkkWbHLan6WZyIyAqKEay0xZUTtUAp39qkGXp/uwbwIX
5LJIaCNyCRpVLrPZprFuzZEEsyrJtujzcy/hJJI/K/KbzzqZOj2CjhYnWfVaNu4ap38uBR+Oz8l8zvPT
UXMdAkDYhKn3yIarixtwMIVr/EqNnLqpOT7s0lEZy8ecGAhhZXZGz1/E89zrV2n85Hxww+tMnWUZfsU9
bg7lbNGEmio+fQ9TJPgFsYt4wFfDATtlbu1RRgHNSoU+c7LrgHs6EVkyUAmjahVCmObtGP1Kcs03OoIz
4db7lP3i+1t0FROUBXdlCR6hLCte66NfPcCu2GVebFiRSILjqdtLh93ujRZsZ1kvLklhrkFH2KOZTp0V
oYlKduO7ylxLxyW5I7iRza/SAZVblZ8Bxy+3vmyXnKeaqITaIsAJ6RoveFGnzQyx+8Czm15TuwFUMEEm
zYK9FMvXcwezxDR4L2D1BfePk8sRjWRq9zVZPzM9NEWwLgJPZSz9Tzl4XGwgKrJXw+3pLl8ncQpkY0nO
b2GyAFZFfk3DvzFX75CI77+iYj/ZrwXEXVanWjPUJbatGlyp/9r6BudvZD+FSmhsl8yDlXpq2ZDymouW
0CCJisfhdW3z2Qhixa0JDxcXDEH/vDA/+NdcbngSOmuXpxB12Oh1vAUsw0cBlqLv7PxnZXXNI3BCP+T3
5Z0fEnrcUMTUCfxQEqq1Mx4A+Kl/L2mtZ39QCBdvhgJRscm3k273JHxKGMCKgfFWHrCpArRd6vQyzK7M
9Mkqi5J2vQhLbEMsPPYS5VkwPsu+rZFPaDACTF/7qVdpIbkDSl2Ts8QOQ5NvMrYvXSqLEPhVcL8OSjpk
0b+d95QXUsMz9bfAeyxX0qReLkBIFiToVKVzpylmoVfahnTe9zfBQ6by5bs4+YLTf5fggwgTaoMnkdnZ
t+H5BB6yl1nucdPK+Tv54R+XIBKRL7xCbHifbkmzRlRk44qfkhxfPnpYFyVkWKJ6CrtKJ4VHdBHvJgyR
TXV5nr8xxUO7chuulxt/UrFuzb+wmbNu4V+fWmJqY0dDQllUvKBTSO5+MlfNBA0O5T6SEnrRa+FEHX3l
wR0sap0/UNhzjKCNkqAP8Qvyn7f3WED8M/B7LMW6xTE4Xx2SaNc3kYVpTYN6lPp1GV7skKI8UE/rqA+x
+OD8xN29NcoconV48tgrzw1JaW448lkg77+XnRZZSZNgTVM3tD36mk4Z7B2jUIghv20MVK/EJz497Ja7
UJCIsZM+IlVJaKpsJ2kggFUMIIBUKADAgESooIBRwSCAUMC4Qkm5oA0fmJZ7qfR5l0MqPMQhDvtvj4XO
ArL56qdQJvyXoCag64zAxIO8PDdpt5JcggXj7XMED5qYGF+jIKp87MOBmdCXb3nAMgDrYsGYRbis3WTW
a8TC8k0Ppn3zRI3vsfgom1r1gNeFSYsA/LK5LMapMtsVnVNsXosRZ/TnmAnR1bvUEcLJho27zxCKUPiH
UQBBU6yeEqlNyJQVawwsfBc8AlrKin7Z/DX4UTT0ZS6IXfldEnyJ5x5x3cDzv+/jR+wN509stN4JVpLV
AYOXXFOb5gLjLwoIQLfHTYg2a/gVtfbToeZ3bX61iTXNKR9MNOYX7oSnZ8IPC4zFnlFlYRYt0u/dtsrj
2zTKfLWkOG4xyG++f1Dwwrgiu1vAgeHf8HINYfnT8x3xSfDHjSwMSl7HLd7Gti8q5zzaVtOrOJUDQ==
> User-Agent: curl/7.33.0
> Host: plhqkafeteria01
> Accept: */*
>
< HTTP/1.1 403 Forbidden
* Server nginx/1.9.2 is not blacklisted
< Server: nginx/1.9.2
< Date: Wed, 15 Jul 2015 07:10:22 GMT
< Content-Type: text/html
< Content-Length: 168
< Connection: keep-alive
<
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.9.2</center>
</body>
</html>
* Connection #0 to host plhqkafeteria01 left intact

**Comment by stnoonan** [comment]
You do not need to specify auth_gss_service_name.
Have you checked the clocks on your client and server versus the clock on the KDCs?

**Comment by Gman1988** [comment]
Yeah i checked and times are the same, they both have the same ntp server.

**Comment by stnoonan** [comment]
Then you'll need to get debug logs for one of these.  Sorry.

**Comment by Gman1988** [comment]
Does the "error_log access.log debug " is correct for nginx config to get the right log verbosity?

**Comment by stnoonan** [comment]
Yes, that should be correct.  As long as you've compiled everything with
--with-debug.
