### ISSUE TITLE
get spnego module part of an existing binary distribution

### ISSUE THREAD

**Issue by ssbarnea** [stnoonan/spnego-http-auth-nginx-module#54]
Adding spnego module to nginx does require recompilation of nginx which is quite hard and risky, clearly not something someone would want to do in a production environment.

Can we have spnego module included in one of the bigger nginx distros? one that would include the spdy one too.

I already raised a feature request against Ubuntu at https://bugs.launchpad.net/nginx/+bug/1486532 -- feel free to support it.

**Comment by stnoonan** [comment]
Ubuntu forwarded this to Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796094 - I commented and answered the maintainer's questions.

**Comment by paulfertser** [comment]
OpenWrt github "pull request" https://github.com/openwrt/packages/pull/1747
