### ISSUE TITLE
CENTOS 6.7 ./config not working

### ISSUE THREAD

**Issue by dbinder64** [stnoonan/spnego-http-auth-nginx-module#56]
All dependencies are installed AFAIK, but ./config doesn't output anything.  Makefile is not updated either.  make runs, but make install errors with "make: *** No rule to make target 'install'. Stop."

Ideas?

**Comment by stnoonan** [comment]
What actual commands are you running?

**Comment by dbinder64** [comment]
I renamed config configure and just ran ./configure.  No results or messages.  Make says change log up to date.  Make install fails.  Bank of america project that is pressing :)



Sent by Outlook for Android





On Sat, Oct 17, 2015 at 7:51 PM -0700, "Sean Timothy Noonan" <notifications@github.com> wrote:










What actual commands are you running?

**Comment by dbinder64** [comment]
I copied the extracted folder to nginx addons folder for the install

**Comment by stnoonan** [comment]
Please read the documentation. This module must be built together with
nginx. It is not a standalone piece of software.

**Comment by dbinder64** [comment]
I tried with add-module but it couldn't find the .o file.  I'll look closer at nginx very build options and config output.Sent from my Verizon Wireless 4G LTE DROIDOn Oct 18, 2015 7:07 AM, Sean Timothy Noonan <notifications@github.com> wrote:Please read the documentation. This module must be built together with
nginx. It is not a standalone piece of software.

**Comment by dbinder64** [comment]
Documentation says download nginx, extract to directory.  It then says to clone the module into the directory (assumption being that it's the same directory nginx was extracted to).  

In the root of nginx-1.9.5, and have a directory spnego-http-auth-nginx-module-master with all the 
files in the zip.

I run  ./configure --prefix=/opt/nginx --user=nginx --group=nginx --with-openssl=/etc/pki/tls --add-module=spnego-http-auth-nginx-module

configure fails with:
./configure: error: no spnego-http-auth-nginx-module/config was found

contents of nginx-1.9.5/spnego-http-auth-nginx-module-master folder are:
README.md
ngx_http_auth_spnego_module.c
Makefile
LICENSE
config
ChangeLog
.gitignore

**Comment by dbinder64** [comment]
All is good now.   I just renamed the folder from spnego-http-auth-nginx-module-master and left off the -master.

Thanks

**Comment by dbinder64** [comment]
The ./configure went well, now make fails with com_err.h: No such file or directory.   I have libs for com_err.

#make
make -f objs/Makefile
make[1]: Entering directory `/home/user1/installs/nginx-1.9.5'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/modules/perl -I src/mail -I src/stream \
                -o objs/addon/spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.o \
                spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.c
spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.c:38:21: error: com_err.h: No such file or directory
make[1]: *** [objs/addon/spnego-http-auth-nginx-module/ngx_http_auth_spnego_module.o] Error 1
make[1]: Leaving directory `/home/nbkvw7l/installs/nginx-1.9.5'
make: *** [build] Error 2

Installed libs:
Package libcom_err-devel-1.41.12-22.el6.x86_64 already installed and latest version
Package libcom_err-1.41.12-22.el6.x86_64 already installed and latest version

**Comment by dbinder64** [comment]
I ended up copying com_err.h to src/core and make succeeded.   I ran make install and no errors.

nginx won't start and says invalid directive "auth_gss on;"

/usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf

contents of conf under server section:

        location / {
            root   html;
            index  index.html index.htm;

            auth_gss on;
            auth_gss_realm GISDEV.COM;
            auth_gss_keytab /home/user1/user1.keytab;
            #auth_gss_service_name  ????
        }
