### ISSUE TITLE
 Add custom fallback if client does not support negotiate (SPENGO Token)  

### ISSUE THREAD

**Issue by harbirg** [stnoonan/spnego-http-auth-nginx-module#58]
In my application, I want to support both Login via login page form or SPENGO. 

If the client supports SPENGO, I use this module and log them in via 'remote-user' attribute. 
If the client does not support negotiation, then instead of enabling 'basic auth fallback', I would rather just have the user still go to the root page but my application would render the sign_in page as 'remote_user' attribute would be nil. I do not want to render the basic auth 'pop-up'. 

I'm unable to achieve my desired outcome, I tried to modify this module by changing NGX_DECLINED to return NGX_OK. Then, I thought I would achieve my outcome as it would return OK in both cases. This causes the client to never attempt SPENGO, the client always go to index page. It seems like each GET / request results in two requests i.e 401 and then WWW-Negotiate

Any ideas on how I achieve my desired outcome and have support for both. 
 

```
ngx_str_t *token_out_b64 = NULL;
    switch(ret) {
        case NGX_DECLINED: /* DECLINED, but not yet FORBIDDEN */
            //ctx->ret = NGX_HTTP_UNAUTHORIZED;
            ctx->ret = NGX_OK; //lets 
            break;
        case NGX_OK:
            ctx->ret = NGX_OK;
            token_out_b64 = &ctx->token_out_b64;
            break;
        case NGX_ERROR:
        default:
            ctx->ret = NGX_HTTP_INTERNAL_SERVER_ERROR;
            break;
    }
```

**Comment by harbirg** [comment]
just came across this and its exactly what I'm asking for https://github.com/stnoonan/spnego-http-auth-nginx-module/issues/30

**Comment by wells** [comment]
At the time, I ended up with a singular route in my web application /auto that tried to perform spnego. The rest of the web app was protected by the app's built-in auth. I did not implement a fallback on that project because all users were all on the domain. 

It would be awesome if an option was implemented to simply passthrough on a failed spnego. The web application would detect the lack of a successful spnego and enforce it's own auth scheme. There may be a security implication if it passes through on failure. First impulse is that it would be fine.

**Comment by harbirg** [comment]
@wells Thanks for your input. I'm investigating this further and understand the spengo protocol to make sure nginx would only permit pass through gracefully if spengo failed and let the web app know. Currently, we can not piggyback on 401 return code as its part of spengo protocol or else I would have just used that as described above. I also came across another issue that is similar to what Im asking for https://github.com/stnoonan/spnego-http-auth-nginx-module/issues/32 error_page 401 semantics.

@stnoonan - if you can provide some input on this or any ideas for issues #32 and #30 would be great.

**Comment by harbirg** [comment]
Adding some notes based on my debug on a spengo vs non-spengo client in the logs and I know understand where the behaviour needs to change for fallback. 

SPENGO Client Timeline 
C: GET dir/index.html
S: HTTP/1.1 401 Unauthorized
S: WWW-Authenticate: Negotiate
C: GET dir/index.html
C: Authorization: Negotiate a87421000492aa874209af8bc028
S: HTTP/1.1 200 Success
S: WWW-Authenticate: Negotiate ade0234568a4209af8bc0280289eca

Non-SPENGO Client Timeline 
C: GET dir/index.html
S: HTTP/1.1 401 Unauthorized
S: WWW-Authenticate: Negotiate
C: GET dir/index.html
C: Authorization: <<nill, client doesnt respond with Negotiate Token>>
Current Response S: HTTP/1.1 401 Unauthorized
Desired Response S: HTTP/1.1 200 OK with special header to notify that Client did not respond with Negotiate Token


My initial thinking is that I need to review the code and see how I can keep state of things, so I know that NGINX has already sent the WWW-Negotiate from Server to Client and it hasnt responded back with Authorization:Negotiate on the second time around - I need to let it go through as its not SPENGO compliant.

**Comment by wells** [comment]
According to a discussion I had with @stnoonan a while ago. Basic auth sets the $remote_user variable. This module initiates a fake basic auth when spnego negotiate is successful.

I had a php backend at the time, and therefore the fake basic auth on a successful spnego was structured as PHP_AUTH_USER = 'username' and PHP_AUTH_PW = 'bogus_auth_gss_passwd'.

**Comment by harbirg** [comment]
After spending some time on this - I feel its best that I handle this via my application by making an ajax request to check if client provided the kerberos ticket. if the ajax GET returns with 401, then I redirect to login page and similarly, if ajax GET returns 200 - then I just read the REMOTE_USER and let them login pass through SSO. I can achieve my desired behaviour and I can use this module without any changes.

Closing this issue -
