### ISSUE TITLE
HTTP ERROR 401 - Authentication Required

### ISSUE THREAD

**Issue by anuvdas** [stnoonan/spnego-http-auth-nginx-module#62]
Hi
I have configured a machine as kerberos client and as a user if i get ticket in the machine i am able to do the HTTP authentication. Also i installed ngnix using your module in the same server. Now my problem is if i try to hit the ngnix from my workstation's browser i am getting authentication required error 401.
So i think ngnix is not able to find the user's kerberos ticket. Any way to specify that in the configuration ?
I have HTTP principal in the keytab file.

Here i am trying to access my cloudera cluster HDFS browser url which is kerberos enabled.

my ngnix conf is like this
location / {
            auth_gss on;
	    auth_gss_realm MYREALM.ORG.COM;
            auth_gss_keytab /etc/http.keytab;
            proxy_pass http://namenode webUI:50070;
}

**Comment by stnoonan** [comment]
It is not clear to me what you are trying to accomplish.

**Comment by anuvdas** [comment]
Okey..let me share the details...
I have a cloudera hadoop cluster (CDH) which is kerberos enabled. Now if users want to access the webHDFS (browse the HDFS data) first they need to login to a kerberos client machine request for a ticket using "kinit" command,then use any browser in that kerberos client machine to connect to WebHDFS.

I want to make this happen from their individual workstations. But then the main problem is, I may have to turn all their workstations to kerberos client so that they can get the kerberos ticket and then authenticate. So someone told me that i can do this with the help of nginx reverse proxy. I installed nginx on the same kerberos client machine.

So i am expecting nginx proxy to do these things...
If the user already has the kerberos ticket, nginx should check the default principal (user@REALM.COM) and service principal say HTTP/hostname@REALM.COM and proxy pass to hadoop webHDFS url.

**Comment by stnoonan** [comment]
This module does not act as a kerberos client.
