### ISSUE TITLE
Is this ngix module still maintained?

### ISSUE THREAD

**Issue by schlauch** [stnoonan/spnego-http-auth-nginx-module#63]
Another question: Do you think that it still works with ngix > 1.7?

**Comment by stnoonan** [comment]
Yes, it is still maintained, in that I still pay attention to it.  I no longer have a personal or work related use for it.

Probably, though I haven't updated it to be a dynamically loadable module.

**Comment by schlauch** [comment]
Thanks. Good to know ☺

Von: Sean Timothy Noonan [mailto:notifications@github.com]
Gesendet: Freitag, 10. Juni 2016 16:46
An: stnoonan/spnego-http-auth-nginx-module
Cc: Schlauch, Tobias; Author
Betreff: Re: [stnoonan/spnego-http-auth-nginx-module] Is this ngix module still maintained? (#63)


Yes, it is still maintained, in that I still pay attention to it. I no longer have a personal or work related use for it.

Probably, though I haven't updated it to be a dynamically loadable module.
