### ISSUE TITLE
plugin returns 403 forbidden on basic auth failure (should return 401)

### ISSUE THREAD

**Issue by AaronOpfer** [stnoonan/spnego-http-auth-nginx-module#67]
The difference between codes 401 and 403 are pretty important. 401 is "Authorization Required" which tells browsers that the credentials they provided are missing or wrong. 403 is "Forbidden" which tells browsers "your credentials worked but you don't have access to that resource."

This plugin returns 403 when the user enters an invalid user and password for basic auth. The result is that the browser will keep the (wrong) credentials and continue to use them whenever visiting the website from that point forward. This is very frustrating for users as they have to close their browser windows and reopen them every time they enter their password wrong.

My work has fixed this by patching these lines:

https://github.com/stnoonan/spnego-http-auth-nginx-module/blob/master/ngx_http_auth_spnego_module.c#L994-L997

``` C
            if (NGX_DECLINED == ngx_http_auth_spnego_basic(r, ctx, alcf)) {
                spnego_debug0("Basic auth failed");
                return (ctx->ret = NGX_HTTP_FORBIDDEN);
            }
```

Replacing NGX_HTTP_FORBIDDEN with NGX_HTTP_UNAUTHORIZED.

**Comment by Squalluca** [comment]
Hi,

i had your same problem, nginx wouldn't ask for new credentials after providing wrong ones, your solution worked for me.
I think you should open a pull request, if you cannot/will not do it, if you don't mind, i will open one requesting the change you provided.
Thanks.

**Comment by AaronOpfer** [comment]
I have changed jobs so I no longer use this plugin. Feel free to do the pull request yourself.
