### ISSUE TITLE
spnego "only one authentication iteration allowed"

### ISSUE THREAD

**Issue by bazsi** [stnoonan/spnego-http-auth-nginx-module#70]
Hi,
I was trying to enable GSSAPI based authentication with an MIT krb5 kdc, nginx and curl, e.g. no Windows AD was present. As I see GSS_S_CONTINUE is not handled, but instead the error message in $SUBJECT is displayed.

Is there any reason in not handling CONTINUE as a minor status? Is there a specific algorithm/setting in the KDC that would generate only a single GSSAPI exchange?

Thanks in advance.

**Comment by lordmauve** [comment]
Is this a duplicate of #64?

**Comment by bazsi** [comment]
Honestly, this was a long time ago, but I did get that error message, otherwise I wouldn't have looked up the code.

And yes, this definitely seems to be a duplicate.

**Comment by stnoonan** [comment]
Duplicate of #64
