### ISSUE TITLE
Support for nginx dynamic modules

### ISSUE THREAD

**Issue by laurivosandi** [stnoonan/spnego-http-auth-nginx-module#75]
Hi,

nginx now supports dynamically loaded modules like Apache.

https://www.nginx.com/resources/wiki/extending/converting/

**Comment by masi** [comment]
Isn't that done with https://github.com/stnoonan/spnego-http-auth-nginx-module/pull/68 ?

But I have to admit that it isn't clear for me if the README should be changed. Like you I have assumed the module is (still) a static one.
