### ISSUE TITLE
Support for optional usage if header is not set

### ISSUE THREAD

**Issue by mlucool** [stnoonan/spnego-http-auth-nginx-module#76]
Is it possible to use this in a `location` only when a specific cookie is not set? Ideally I'd like to use secure cookies with a fallback to to auth_gss only when the cookie is not present (or ideally, not valid, but this can be handled by just clearing the cookie).

**Comment by stnoonan** [comment]
nginx configs might be able to pull that off, but I've got no advice for you. When we wanted that behavior, we did the GSS auth in our backend.
