### ISSUE TITLE
default http2_max_field_size insufficient for larger FQDNs

### ISSUE THREAD

**Issue by asherct** [stnoonan/spnego-http-auth-nginx-module#77]
I was getting connection errors with my FQDN (e.g. https://hostname.subdomain.example.com), though the unqualified domain name (https://hostname) worked fine worked fine. Turning on debug in my error_log, I found:
`client exceeded http2_max_field_size limit while processing HTTP/2 connection`
I upped it from the default 4k to 8k by adding the line:
`http2_max_field_size 8k;`
I don't think this is a bug, but perhaps it should be noted in the **Troubleshooting** section of the readme under the **Increase maximum allowed header size** subheading?

**Comment by stnoonan** [comment]
If you send a pull request, I'd be happy to accept it. I'm not sure this is related to this module.
