### ISSUE TITLE
403 gss_accept_sec_context() failed: Unknown error

### ISSUE THREAD

**Issue by fote** [stnoonan/spnego-http-auth-nginx-module#78]
Hello
I have some trouble when i trying to set up spnego-http-auth-nginx-module:

Here my nginx.conf:
```
 auth_gss on;
 auth_gss_realm PLAY.DC;
 auth_gss_keytab /administrator.keytab;
 auth_gss_service_name HTTP/administrator;
```

Time on nginx server:
```
# date
Mon Oct 16 20:31:07 UTC 2017
```

And here debug log:
```
2017/10/16 20:22:26 [debug] 1023#0: *206 Token decoded: TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKANc6AAAADw==
2017/10/16 20:22:26 [debug] 1023#0: *206 Client sent a reasonable Negotiate header
2017/10/16 20:22:26 [debug] 1023#0: *206 GSSAPI authorizing
2017/10/16 20:22:26 [debug] 1023#0: *206 Use keytab /administrator.keytab
2017/10/16 20:22:26 [debug] 1023#0: *206 gss_accept_sec_context() failed: Unknown error:
2017/10/16 20:22:26 [debug] 1023#0: *206 GSSAPI failed
2017/10/16 20:22:26 [debug] 1023#0: *206 http finalize request: 403, "/?" a:1, c:1
2017/10/16 20:22:26 [debug] 1023#0: *206 http special response: 403, "/?"
2017/10/16 20:22:26 [debug] 1023#0: *206 http set discard body
2017/10/16 20:22:26 [debug] 1023#0: *206 xslt filter header
2017/10/16 20:22:26 [debug] 1023#0: *206 HTTP/1.1 403 Forbidden
```

```
# klist -kt /administrator.keytab
Keytab name: FILE:/administrator.keytab
KVNO Timestamp           Principal
---- ------------------- ------------------------------------------------------
   1 10/16/2017 15:56:04 administrator@PLAY.DC
   1 10/16/2017 15:56:04 administrator@PLAY.DC
   1 10/16/2017 15:57:50 HTTP/administrator@PLAY.DC
   1 10/16/2017 15:57:50 HTTP/administrator@PLAY.DC
```

```
# ls -la /administrator.keytab
-rw------- 1 www-data www-data 298 Oct 16 15:57 /administrator.keytab
```

I created keytab file with this command:
`kadmin.local -q "xst -norandkey -k administrator.keytab HTTP/administrator"`

and it works when i use kinit:
```
# kinit -V -k -t administrator.keytab  HTTP/administrator@PLAY.DC
Using default cache: /tmp/krb5cc_0
Using principal: HTTP/administrator@PLAY.DC
Using keytab: administrator.keytab
Authenticated to Kerberos v5
```

**Comment by avengerweb** [comment]
Your client sent ```NTLMSSP``` which not supported by this module.

**Comment by theciezac** [comment]
I had encountered a similar issue with the same `gss_accept_sec_context() failed: Unknown error:`

I was running nginx in a docker container (in a Linux machine) and I have mistakenly listed the `auth_gss_keytab` path name of the keytab file to the Linux machine directory instead of the Docker container directory.

`auth_gss_keytab /linuxOSPath/path/to/<...>/keytabfile.keytab`
should be
`auth_gss_keytab /dockerContainerPath/to/<...>/keytabfile.keytab`

where host directory is `/linuxOSPath/to/` and container is `/dockerContainerPath/to/`

This is probably not a solution to your issue, but I think it should be worth sharing here.

**Comment by Flyguy** [comment]
> Your client sent `NTLMSSP` which not supported by this module, so painfully to debug...

My windows machine sent it too. I had windows 7 && (firefox || IE || Chrome || Custom C# application).
How can I change this behavior ??

**Comment by stnoonan** [comment]
It's a client configuration issue; one of the forks has a nice detailed setup guide for Windows machines.
