### ISSUE TITLE
A way to disable 401 for unauthorized users?

### ISSUE THREAD

**Issue by c0ncr3t3fa1ry** [stnoonan/spnego-http-auth-nginx-module#80]
Greetings, @stnoonan 
Thank you for your work, your module is very handy, but i can't set it up for my case :(
My case is to authorize users with token, and send their username to my web-app backend and magic will happen there, but if there is no token, and user is not authorized - 401 should not happen, page should be loaded as always (./auth.php, for example).
Any way to reach my goal?

**Comment by martvaha** [comment]
@c0ncr3t3fa1ry Have you read the advice from #30? The proposed solution is to redirect 403 errors to a different page.

**Comment by c0ncr3t3fa1ry** [comment]
@martvaha Sir, could you, please, explain this to me? I read that issue, but did not get the point - i am not getting 403, i am getting 401. I just did that after your comment, but it didnt helped. Or you mean change something in module code?
Thank you!

**Comment by martvaha** [comment]
I'm not sure I understand what you mean with your last sentence. However, as I understand it, 401 does not mean the authentication has failed, its just an intermediate step. If the authentication fails you should get an 403 error that you can redirect as you need. Hope this helps!

**Comment by c0ncr3t3fa1ry** [comment]
@martvaha The fact is - i am actually getting 401 as a final response code for user without negotiation header...

**Comment by c0ncr3t3fa1ry** [comment]
I get it... I am getting 403 from windows machine, and 401 from linux machine... Any way to pass that?

**Comment by toyomsk** [comment]
> I get it... I am getting 403 from windows machine, and 401 from linux machine - with completely empty negotiate header... Any way to pass that?
> And also when trying to access resource from windows machine without legit token still getting an single basic fallback, even with auth_gss_allow_basic_fallback off;
> After clicking cancel it does not ask me for it again, but still annoying for users :c

Are you solved problem with clicking cancel?

**Comment by stnoonan** [comment]
The logic is probably possible to implement, but it sounds like these are misconfigured clients.
