### ISSUE TITLE
Basic auth fails when we send user name with domain name.

### ISSUE THREAD

**Issue by sathishgovindan** [stnoonan/spnego-http-auth-nginx-module#93]
What I found was basic auth works for user_name alone but not for domain\user_name.

FYI: Even this is happening when server and user in the same domain.

**Comment by stnoonan** [comment]
IIRC https://github.com/stnoonan/spnego-http-auth-nginx-module/blob/master/ngx_http_auth_spnego_module.c#L340 we only support the hardcoded realm for basic auth. Feel free to send a pull request expanding that support.
