### ISSUE TITLE
auth_ldap

### ISSUE THREAD

**Issue by keith6014** [stnoonan/spnego-http-auth-nginx-module#97]
Has anyone gotten, auth_ldap (https://github.com/kvspb/nginx-auth-ldap) to work with auth_gss? 

I would like to do authentication with auth_gss and authorization with auth_ldap

**Comment by keith6014** [comment]
anyone?

**Comment by hawicz** [comment]
If you're authenticating with auth_gss, you aren't going to have a user's password to try to authenticate against an ldap server with, so what do you mean by "work with"?

**Comment by keith6014** [comment]
I though I can get authorization information from auth_gss.  Seems I can only get username. Ok, its good to know its not possible.

**Comment by hawicz** [comment]
d'oh, I didn't read your original question closely enough and didn't realize you wanted to use auth_ldap for authorization, not authentication.

Poking around in the code a bit, it seems that auth_ldap always expects to get it's user information from the Authorization header with Basic auth.  If there was some way to tell auth_ldap to skip trying to do that, it might be possible for it to pick up the user that auth_gss set in "r->headers_in.user", but you'd need to hack on a code a bit.  Also, I have no idea how to ensure that the modules get called in the right order.
